### ISSUE TITLE
🐛 Bug Report: python function execution giving this error : `An internal curl error has occurred within the executor! Error Msg: Could not resolve host: 63c394095cd05bd-6400ec59364d8`

### ISSUE THREAD

**Issue by hemangjoshi37a** [appwrite/functions-starter#48]
### 👟 Reproduction steps

I ran my python function and it is giving me this error.
```
An internal curl error has occurred within the executor! Error Msg: Could not resolve host: 63c394095cd05bd-6400ec59364d8
```

### 👍 Expected behavior

Should run successfully

### 👎 Actual Behavior

not runnig well and giving error

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

everything standard and latest

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@hemangjoshi37a, if you're receiving this error with every function execution, there might be something wrong with your code. If it happens randomly, you might be affected by one of these related issues:

* https://github.com/appwrite/appwrite/issues/5233
* https://github.com/appwrite/appwrite/issues/3776

As such, I'm going to close this issue. If you still need help, feel free to create a [support](https://discord.com/channels/564160730845151244/1072905050399191082) post on our [Discord](https://appwrite.io/discord).
