### ISSUE TITLE
🚀 Feature: Java documentation

### ISSUE THREAD

**Issue by ai-developer63** [appwrite/functions-starter#49]
### 🔖 Feature description

I have been using Firebase for long period of time and able to use it perfectly but sad news is that it charges more when we will grow up and appwrite as alternative but when i started to learn it for java but it doesn't have an documentation for JAVA android. I have searched everypart of internet but didn't get it. If anyone can than please create it and update in the main documentation which will really boost appwrite. Thank you for your support and expecting updated docs with JAVA android soon

### 🎤 Pitch

If Documentation of Appwrite is added in JAVA than it will really help real donator as an it will indirectly attract biggest investor as successful project are mainly in JAVA as android developer. In context of me, i have 7 app running i want to bring it in appwrite but lack of documentation make me sad.  This is my request that if any one can create a course in java or Only update Documentation makes it great.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@ai-developer63, thanks for creating this issue! 🙏🏼 What documentation are you referring to? This repo is for Appwrite Functions 🧐

**Comment by ai-developer63** [comment]
https://appwrite.io/docs/tutorials/android/ this doc needs lots of improvement. From last view it have improved good. I will try it. Soon

**Comment by stnguyen90** [comment]
Closing as issue is unrelated to Appwrite function starters
