### ISSUE TITLE
🚀 Feature: Symfony support in cloud functions 

### ISSUE THREAD

**Issue by HeavyMedaI** [appwrite/functions-starter#50]
### 🔖 Feature description

Hello,

I would like to use Symfony 6 in cloud functions but I could not find any documentation for it. Is it possible to use Symfony at all or do you have any plan for implementing framework support.

### 🎤 Pitch

About using frameworks in cloud functions.

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
You can install Symfony into the PHP runtime in appwrite. However, our runtimes currently do not support a full HTTP server. Hopefully with https://github.com/appwrite/appwrite/discussions/5016 it would be possible, please add your feedback to the discussion, thanks!

**Comment by HeavyMedaI** [comment]
It's a little late but thank you for your answer. I am using some of Symfony's components in functions and it's great so far. Right now I am working on a function that generates database collections with attributes and indexes defined in an xml migration file based on Doctrine ORM xml standards. I may share it with community but I am not sure where to announce it yet.

<img width="1314" alt="Ekran Resmi 2023-08-01 22 09 11" src="https://github.com/appwrite/functions-starter/assets/6917144/aa64d8cb-caa1-48b6-8de9-94e6535f3a1f">
