### ISSUE TITLE
🐛 Bug Report: Deno runtime appwrite dependency

### ISSUE THREAD

**Issue by ibanks42** [appwrite/functions-starter#52]
### 👟 Reproduction steps

Run `appwrite init function` and select the deno runtime.
Deploy the function.

### 👍 Expected behavior

It should deploy.

### 👎 Actual Behavior

It fails to deploy due to importing `https://deno.land/x/appwrite@6.0.0/mod.ts` in `src/deps.ts`.
This version is broken due to `https://deno.land/x/appwrite@6.0.0/src/inputFile.ts` importing `https://deno.land/std/streams/conversion.ts` which does not exist anymore.
This is fixed in `https://deno.land/x/appwrite@7.0.0/src/inputFile.ts`

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Server is running v1.3.7 on docker on a macos server. I have added the deno runtime to the runtime list. Other than that and cloudflare as my proxy, not much is very customized.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by loks0n** [comment]
fixed with https://github.com/appwrite/functions-starter/pull/64
