### ISSUE TITLE
🐛 Bug Report: Outdated node-appwrite version in node starter templates

### ISSUE THREAD

**Issue by PaulDotterer** [appwrite/functions-starter#62]
### 👟 Reproduction steps

When using the CLI to init a new function, the template that gets pulled down it only contains node-appwrite version `^9.0.0`
When the function get build with that version things like `Role.label("xxx")` don't work because its not inside this sdk version.
Updating this manually resolves the issue, but it is rather annoying to change that for every function that gets created

### 👍 Expected behavior

Pull the latest SDK version when that becomes available

### 👎 Actual Behavior

Pulls latest 9.x.x version

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Appwrite 1.4.13
Running on Raspberry Pi 4B with docker

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by loks0n** [comment]
fixed with https://github.com/appwrite/functions-starter/pull/64
